# -*- coding: utf-8 -*-
"""Dati dei 7 giorni 24→30 settembre 2026. Generato dall'ingestione del 24/09."""

PESO = 75.7
BMR = 1761.0
BASE = round(BMR * 1.3)          # 2289 kcal
FTP = 297.0                      # Regola 18

DAYS = [
 dict(iso="2026-09-24", titolo="Giovedì 24 settembre", tag="media", dot="warn",
      kcal=3327, C=454, P=136, G=107, cpk=6.0, ppk=1.8,
      needn="2.289 kcal di base (BMR × 1,3) + <b>888 kcal</b> di corsa a piano + <b>150 kcal</b> di yoga. Se la corsa salta, togli 888 kcal (≈220 g di carboidrati).",
      sessions=[
        dict(icon="🏃", nome="recupero attivo", sub="Corsa · pianificata (TrainingPeaks)", kcal="888 kcal",
             metrics=["⏱ 0:50", "📏 10,67 km", "⚡ TSS 33,3"],
             nota="1 kcal/kg/km × 10,67 km <b>+10% su strada</b> (sei verifiche, media +8,7%). A 0:50 per 10,67 km il passo a piano è 4:41/km: per un «recupero attivo» è alto — se lo corri davvero piano la spesa scende verso 800 kcal."),
        dict(icon="🧘", nome="yoga core+allungamento", sub="Other · pianificata", kcal="150 kcal",
             metrics=["⏱ n.d.", "⚡ TSS 15,0"],
             nota="Durata non indicata su TrainingPeaks. Stima prudente a 150 kcal."),
      ],
      flags=[("pend", "⏳ <b>Giornata aperta.</b> COROS è fermo a <b>1.132 passi · 123 kcal · 0 minuti</b>: nessun verdetto oggi (<b>Regola 12</b>). Il 21/09 la corsa è partita alle 19:13, oltre un'ora dopo il run di ingestione.")],
      insight=[
        "<b>Ieri è stata una giornata doppia, e nessuna delle due sedute era in calendario lì.</b> Bici «Z4 reps-pianura» 07:27 → 09:04 (<b>35,95 km · 1:36:52 · +476 m · 1.385 kcal</b>, Garmin) e nuoto in vasca 13:09 → 13:50 (<b>3,03 km · 41:04 · 369 kcal · TL 56 · HR 147</b>, COROS). Finestre orarie disgiunte: sono <b>entrambe reali</b>, non un doppione.",
        "<b>La Z4 non era saltata martedì: era stata spostata.</b> Stesso titolo, stessa struttura, un giorno dopo. È il primo caso del blocco in cui una seduta pianificata viene traslata invece che sostituita o persa — martedì resta un riposo pieno (3.604 passi, 243 kcal, 0 minuti, Garmin senza uscite).",
        "<b>Il nuoto è arrivato di iniziativa tua</b>, senza essere a piano: il primo dal 16/09 e il primo mai registrato fuori calendario. Rompe il pattern delle cinque sedute in vasca saltate su sei. Costo energetico misurato <b>121,8 kcal/km</b>, sotto il range delle quattro misure precedenti (128-159): la media su cinque misure scende a ~138 e in dashboard il coefficiente passa a <b>141 kcal/km</b>.",
        "<b>Il conto della durata resta però aperto</b>: 1:05 a piano, 1:36:52 reali, <b>+49%</b>. È l'ottava sforata su dodici uscite outdoor brevi con un target. E TrainingPeaks dà <code>tss_actual</code> = <b>0,7</b> sulla bici — valore corrotto senza misuratore di potenza (Regola 20): il TSS ricostruito dall'IF della pianificata è <b>~92</b>.",
        "<b>Il corpo non ha presentato il conto</b>: la notte dopo ha dato 8h27, score 87, HRV 114 e RHR 48. Tre notti consecutive nella metà alta del range dopo il crollo di domenica.",
      ],
      recovery=dict(
        rows=[("HRV notturna", "good", "<b>113 ms</b> · Normal", "range 76-122, baseline 99 (ferma da quattro giorni). Terza notte di fila nella metà alta: 122 → 114 → <b>113</b>"),
              ("Sonno 23→24/09", "good", "<b>7h32</b> · score 82", "deep <b>30%</b> · REM 10% · efficienza 97,2% · 22:47 → 06:32 · sleep HR 46"),
              ("FC a riposo", "good", "<b>50 bpm</b>", "49 → 48 → 50: stabile sul fondo del range 45-58"),
              ("Recovery / carico", "good", "<b>100%</b> · ratio <b>0,79</b>", "«Performance», short 53 / long 67 (valore del giorno, provvisorio). Limite inferiore: ~878 TSS di bici non sono mai entrati nel modello COROS")],
        nota="🟢 <b>Finestra pulita, ma il REM si sta assottigliando</b>: 24% → 14% → <b>10%</b> in tre notti, mentre il deep tiene (26 → 27 → 30%). Non è ancora un problema — durata, HRV e RHR sono tutti buoni — ma è lo stesso indicatore che precedeva il crollo del 20/09. <b>Il test vero è il weekend</b>: 26-27/09 ripete la struttura di carico del 19-20/09 (3 h di bici + corsa collinare), che allora aveva prodotto HRV 48 e REM al 4%. Oggi e domani vanno tenuti leggeri per davvero, e a letto entro le 23:00."),
      ),
 dict(iso="2026-09-25", titolo="Venerdì 25 settembre", tag="media", dot="warn",
      kcal=2783, C=363, P=136, G=87, cpk=4.8, ppk=1.8,
      needn="2.289 kcal di base (BMR × 1,3) + <b>494 kcal</b> di nuoto a piano. Se il nuoto salta, togli 494 kcal (≈120 g di carboidrati).",
      sessions=[
        dict(icon="🏊", nome="velocità+B2 incrementale", sub="Nuoto in vasca · pianificata", kcal="494 kcal",
             metrics=["⏱ 0:45", "📏 3,5 km", "⚡ TSS 68,9"],
             nota="<b>141 kcal/km</b> × 3,5 km — coefficiente aggiornato con la quinta misura del 23/09 (121,8 kcal/km), range 122-159.<br>200 riscaldamento · 6×50 tecnica · 12×25 sprint 15″ rec · 6× (50 forti / 50 sciolti / 75 forti / 75 sciolti / 100 forti / 100 sciolti)."),
      ],
      flags=[("warnb", "🟢 <b>Sesta vasca a piano — ma il quadro è cambiato.</b> Cinque delle sei precedenti erano saltate; mercoledì però la vasca è arrivata <b>senza</b> essere pianificata, 3,03 km. <b>Regola 19</b>: il TSS del nuoto resta carico opzionale finché non compare il record."),],
      insight=None, recovery=None),
 dict(iso="2026-09-26", titolo="Sabato 26 settembre", tag="lunga · facile", dot="crit",
      kcal=4606, C=757, P=144, G=111, cpk=10.0, ppk=1.9,
      needn="2.289 kcal di base (BMR × 1,3) + <b>2.317 kcal</b> di bici. Proteine a <b>1,9 g/kg</b>: su 757 g di carboidrati gli alimenti ammessi ne portano comunque ~100 g, alzare il target è più onesto che dichiarare uno scarto. Il fueling copre una parte del totale: vedi sotto.",
      sessions=[
        dict(icon="🚴", nome="facile", sub="Bici · pianificata · uscita libera", kcal="2.317 kcal",
             metrics=["⏱ 3:00", "⚡ TSS n.d. (~142)", "NP ~204 W"],
             nota="TrainingPeaks non dà il TSS. Stima dall'uscita gemella del 19/09 (stessa voce «uscita libera, tetto 175 bpm», IF 0,688): NP = 0,688 × 297 = 204 W → 204 × 10.800 / 1.000 = 2.207 kcal, <b>+5% sulle uscite ≥ 3 h</b> (Regola 18)."),
      ],
      flags=[("warnb", "⚠️ <b>Il 19/09 questa stessa «uscita libera» da 3:00 è durata 4:10 (+39%)</b>, 132 km e 3.268 kcal. Se esci per quattro ore aggiungi ~780 kcal e un gel ogni 40 minuti in più."),
             ("dev", "📐 <b>È la seduta su cui si riverifica la Regola 18</b> (FTP 297 W + 5% sulle lunghe). Le ultime due prove hanno dato −1,5% e −6,0%.")],
      fuel=dict(titolo="⚡ Fueling della bici lunga",
        pre="Pre = la colazione già pianificata, 2-3 h prima della partenza. Caffeina 150-190 mg (2-2,5 mg/kg) se parti presto.",
        intra_note="3 gel + 1,5 L di isotonica + 1 banana su 3 h: ~63 g di carboidrati/ora, adatto a un ritmo facile con tetto 175 bpm.",
        intra=[("Gel (1 pz = 32 g)", 96), ("Bevanda isotonica", 1500), ("Banana", 120)],
        post_note="Entro 30-45 minuti dall'arrivo.",
        post=[("Whey", 30), ("Corn flakes s/zuccheri", 60), ("Latte di soia", 250)]),
      insight=None, recovery=None),
 dict(iso="2026-09-27", titolo="Domenica 27 settembre", tag="media", dot="crit",
      kcal=3471, C=530, P=136, G=90, cpk=7.0, ppk=1.8,
      needn="2.289 kcal di base (BMR × 1,3) + <b>1.182 kcal</b> di corsa. Il fueling ne copre una parte: vedi sotto.",
      sessions=[
        dict(icon="🏃", nome="facile collinare", sub="Corsa · pianificata", kcal="1.182 kcal",
             metrics=["⏱ 1:20", "📏 ~14,2 km", "⚡ TSS 89,1"],
             nota="1 kcal/kg/km × 14,2 km stimati +10% su strada. Dopo 15′ di riscaldamento in pianura, 3 salite corte (&lt;1 km) e non ripide. &lt;180 bpm in pianura, ~185 bpm in salita."),
      ],
      flags=[("warnb", "⚠️ <b>Il weekend 26-27/09 ripete esattamente la struttura del 19-20/09</b>: 3 h di bici il sabato, corsa la domenica. Quel weekend aveva prodotto <b>HRV 48 ms «Low»</b>, sonno 6h26 e REM al 4%. La differenza che puoi controllare è l'orario: entrambe le notti del 19-20/09 sono iniziate <b>dopo mezzanotte</b>.")],
      fuel=dict(titolo="⚡ Fueling della corsa collinare",
        pre="Pre = la colazione già pianificata, 2-3 h prima. Sul collinare meglio leggera: niente grassi né fibre nelle ultime 2 h.",
        intra_note="1 gel a metà + 500 ml di isotonica: ~41 g di carboidrati/ora, sufficienti per 1h20 a intensità controllata.",
        intra=[("Gel (1 pz = 32 g)", 32), ("Bevanda isotonica", 500)],
        post_note="Entro 30-45 minuti dall'arrivo.",
        post=[("Whey", 30), ("Banana", 120)]),
      insight=None, recovery=None),
 dict(iso="2026-09-28", titolo="Lunedì 28 settembre", tag="leggera", dot="good",
      kcal=2579, C=265, P=151, G=102, cpk=3.5, ppk=2.0,
      needn="2.289 kcal di base (BMR × 1,3) + <b>290 kcal</b> di forza. Giornata a basso carboidrato: proteine a <b>2,0 g/kg</b> come in tutti i giorni di forza.",
      sessions=[
        dict(icon="🏋️", nome="Gambe Mantenimento", sub="Forza · pianificata", kcal="290 kcal",
             metrics=["⏱ ~0:57", "⚡ TSS 20,0"],
             nota="309 kcal/h (quattro misure COROS, range 275-337) × ~57′. Durata non indicata su TrainingPeaks."),
      ],
      flags=[("dev", "🔵 <b>È la seduta saltata martedì 22/09 e mai recuperata</b>, ora riprogrammata. A differenza della Z4 bici — spostata di un giorno e svolta — questa era rimasta indietro: il doppione temuto la settimana scorsa non c'è stato.")],
      insight=None, recovery=None),
 dict(iso="2026-09-29", titolo="Martedì 29 settembre", tag="media", dot="warn",
      kcal=2797, C=363, P=136, G=89, cpk=4.8, ppk=1.8,
      needn="2.289 kcal di base (BMR × 1,3) + <b>508 kcal</b> di nuoto a piano. Se il nuoto salta, togli 508 kcal (≈125 g di carboidrati).",
      sessions=[
        dict(icon="🏊", nome="braccia+A2", sub="Nuoto in vasca · pianificata", kcal="508 kcal",
             metrics=["⏱ 0:46", "📏 3,6 km", "⚡ TSS 71,8"],
             nota="141 kcal/km × 3,6 km.<br>200 riscaldamento · 6×50 tecnica con boccaglio · 6×50 R8 · 12×50 pale+pull · 6×50 A2 · 8×50 pale+pull · 4×50 A2 · 4×50 pale+pull · 2×50 A2 · 10×100 con boccaglio ampiezza max."),
      ],
      flags=[("warnb", "🔴 <b>Settima vasca a piano.</b> È la seduta più lunga del blocco (3,6 km, 71,8 TSS) e arriva due giorni dopo il weekend carico: è la prima candidata a saltare se il recupero non tiene.")],
      insight=None, recovery=None),
 dict(iso="2026-09-30", titolo="Mercoledì 30 settembre", tag="media", dot="warn",
      kcal=3638, C=568, P=136, G=91, cpk=7.5, ppk=1.8,
      needn="2.289 kcal di base (BMR × 1,3) + <b>1.349 kcal</b> di bici. Il fueling ne copre una parte: vedi sotto.",
      sessions=[
        dict(icon="🚴", nome="variazioni Z2/Z3", sub="Bici · pianificata · ⭐ principale", kcal="1.349 kcal",
             metrics=["⏱ 1:48", "⚡ TSS 88,4", "NP ~208 W"],
             nota="NP = 297 × √(0,8842 / 1,8) = 208 W → 208 × 6.480 / 1.000 = <b>1.349 kcal</b>. Variazioni da fare in pianura. Sotto le 3 h non si applica il +5%, ma con dislivello marcato il 23/09 ha dato −6,0%: se il percorso sale, aggiungi ~80 kcal."),
      ],
      flags=[("dev", "🔀 <b>Due voci «variazioni Z2/Z3» sullo stesso giorno = alternative, non si sommano.</b> La seconda vale 0:57 e 49,63 TSS (~760 kcal): se scegli quella, togli <b>589 kcal</b> dal fabbisogno (≈145 g di carboidrati) e dimezza il fueling.")],
      fuel=dict(titolo="⚡ Fueling della bici",
        pre="Pre = il pasto già pianificato, 2-3 h prima.",
        intra_note="2 gel + 750 ml di isotonica su 1h48: ~53 g di carboidrati/ora, adeguati a un lavoro Z2/Z3.",
        intra=[("Gel (1 pz = 32 g)", 64), ("Bevanda isotonica", 750)],
        post_note="Entro 30-45 minuti dall'arrivo.",
        post=[("Whey", 30), ("Gallette di riso", 20)]),
      insight=None, recovery=None),
]
