# -*- coding: utf-8 -*-
"""Dati dei 7 giorni 25 settembre → 1 ottobre 2026. Generato dall'ingestione del 25/09."""

PESO = 75.7
BMR = 1761.0
BASE = round(BMR * 1.3)          # 2289 kcal
FTP = 297.0                      # Regola 18

DAYS = [
 dict(iso="2026-09-25", titolo="Venerdì 25 settembre", tag="media", dot="warn",
      kcal=2783, C=363, P=136, G=87, cpk=4.8, ppk=1.8,
      needn="2.289 kcal di base (BMR × 1,3) + <b>494 kcal</b> di nuoto a piano. Se il nuoto salta, togli 494 kcal (≈120 g di carboidrati).",
      sessions=[
        dict(icon="🏊", nome="velocità+B2 incrementale", sub="Nuoto in vasca · pianificata", kcal="494 kcal",
             metrics=["⏱ 0:45", "📏 3,5 km", "⚡ TSS 68,9"],
             nota="<b>141 kcal/km</b> × 3,5 km (cinque misure, range 122-159).<br>200 riscaldamento · 6×50 tecnica · 12×25 sprint 15″ rec · 6× (50 forti 10″ rec / 50 sciolti 5″ rec / 75 forti 15″ rec / 75 sciolti 10″ rec / 100 forti 20″ rec / 100 sciolti 10″ rec)."),
      ],
      flags=[("pend", "⏳ <b>Giornata aperta.</b> COROS è fermo a <b>1.785 passi · 182 kcal · 0 minuti</b> alle 18:11: nessun verdetto oggi (<b>Regola 12</b>). <b>Ieri la corsa è partita alle 18:14 — due minuti dopo la chiusura del run di ingestione delle 18:12.</b> È la conferma più netta che la Regola 12 abbia mai avuto."),
             ("warnb", "🟢 <b>Sesta vasca a piano — e il quadro è cambiato.</b> Cinque delle sei precedenti sono saltate, ma mercoledì 23/09 la vasca è arrivata <b>senza</b> essere pianificata (3,03 km). <b>Regola 19 e corollario</b>: il TSS del nuoto resta carico opzionale finché non compare il record."),],
      insight=[
        "<b>Il «recupero attivo» di ieri non era un recupero.</b> 10,12 km in <b>49:02</b> a 4:51/km, <b>HR media 164 bpm</b>, potenza media 271 W, <b>TL 111</b>. A piano c'erano 33,32 TSS; TrainingPeaks ne ha registrati <b>51,82</b> (+56%) e il carico COROS è <b>3,3 volte</b> quello previsto. L'orologio stesso ha chiuso con «Performance: Below Average» — per una seduta di scarico è il segnale che è stata corsa troppo forte, non troppo piano. Partita alle <b>18:14</b>, chiusa alle <b>19:03</b>.",
        "<b>Terzo caso consecutivo di seduta traslata (Regola 21).</b> Quella corsa era pianificata il 23/09 ed era ancora «planned» al run di ieri: non era saltata, era slittata di un giorno. Bici 22→23, corsa 23→24: il piano scorre, non perde sedute.",
        "<b>Lo yoga di ieri invece è andato perso davvero</b> (15 TSS): è ancora «planned» sul 24/09 e lo stesso titolo non ricompare da qui al 02/10. Escluso il caso Regola 21, si dichiara saltato.",
        "<b>Regola 8 — undicesima validazione, terzo centro esatto.</b> 62 + 7 × (69 − 62) = <b>111</b> contro un TL misurato di <b>111</b>: scarto 0%.",
        "<b>Il coefficiente della corsa si assesta.</b> Previsti 766 kcal (1 kcal/kg/km), misurati <b>817</b>: +6,6%, settima verifica su strada. La media scende da +8,7% a <b>+8,4%</b>, ed è il valore usato da qui in avanti nei preventivi.",
        "<b>E il corpo ha risposto bene:</b> la notte successiva ha dato 7h40, score 85, <b>REM di nuovo al 17%</b> (era al 10%), deep 31%, <b>HRV 121 ms</b> — al massimo del range — e RHR 49. Il calo di REM delle tre notti precedenti si è invertito proprio alla vigilia del weekend di carico.",
      ],
      recovery=dict(
        rows=[("HRV notturna", "good", "<b>121 ms</b> · Normal", "range 76-122, baseline 99. <b>Quinta notte Normal di fila</b> e la più alta del blocco: 114 → 113 → <b>121</b>, praticamente sul tetto del range"),
              ("Sonno 24→25/09", "good", "<b>7h40</b> · score 85", "deep 31% · <b>REM 17%</b> (da 10%) · efficienza 98,3% · 22:37 → 06:25 · sleep HR 47"),
              ("FC a riposo", "good", "<b>49 bpm</b>", "48 → 50 → 49: quattro giorni sul fondo del range 45-58"),
              ("Recovery / carico", "good", "<b>100%</b> · ratio <b>0,86</b>", "«Heavy training allowed», 0h di recupero residuo. Short 59 / long 68 (valore del giorno, provvisorio); il 24/09 si è assestato a <b>0,98</b>. Limite inferiore: ~878 TSS di bici non sono mai entrati nel modello COROS")],
        nota="🟢 <b>Non c'è un indicatore fuori posto: è la finestra più pulita del blocco.</b> HRV al massimo del range, REM rientrato, RHR basso, recovery pieno. <b>Il che rende il weekend il vero test</b>: 26-27/09 ripete la struttura del 19-20/09 (3 h di bici il sabato, corsa collinare la domenica), e quel weekend aveva prodotto HRV 48 ms «Low», sonno 6h26 e REM al 4%. La differenza non era il carico ma l'orario: entrambe quelle notti sono iniziate <b>dopo mezzanotte</b>, mentre le ultime tre sono iniziate prima delle 23:00. <b>Quella è la leva.</b> Oggi in vasca vai secondo programma; il conto si paga domenica sera, non sabato."),
      ),
 dict(iso="2026-09-26", titolo="Sabato 26 settembre", tag="lunga · facile", dot="crit",
      kcal=4606, C=757, P=144, G=111, cpk=10.0, ppk=1.9,
      needn="2.289 kcal di base (BMR × 1,3) + <b>2.317 kcal</b> di bici. Proteine a <b>1,9 g/kg</b>: su 757 g di carboidrati gli alimenti ammessi ne portano comunque ~100 g, alzare il target è più onesto che dichiarare uno scarto. Il fueling copre una parte del totale: vedi sotto.",
      sessions=[
        dict(icon="🚴", nome="facile", sub="Bici · pianificata · uscita libera", kcal="2.317 kcal",
             metrics=["⏱ 3:00", "⚡ TSS n.d. (~142)", "NP ~204 W"],
             nota="TrainingPeaks non dà il TSS. Stima dall'uscita gemella del 19/09 (stessa voce «uscita libera, tetto 175 bpm», IF 0,688): NP = 0,688 × 297 = 204 W → 204 × 10.800 / 1.000 = 2.207 kcal, <b>+5% sulle uscite ≥ 3 h</b> (Regola 18)."),
      ],
      flags=[("warnb", "⚠️ <b>Il 19/09 questa stessa «uscita libera» da 3:00 è durata 4:10 (+39%)</b>, 132 km e 3.268 kcal. Se esci per quattro ore aggiungi ~780 kcal e un gel ogni 40 minuti in più."),
             ("dev", "📐 <b>È la seduta su cui si riverifica la Regola 18</b> (FTP 297 W, +5% sulle uscite ≥ 3 h). Le ultime due prove hanno dato −1,5% e −6,0%."),
             ("warnb", "🔴 <b>Tetto 175 bpm: rispettalo davvero.</b> Ieri una seduta etichettata «recupero» è finita a HR media 164. Se sabato la «facile» sale allo stesso modo, il weekend diventa il 19-20/09 anche nei numeri del recupero.")],
      fuel=dict(titolo="⚡ Fueling della bici lunga",
        pre="Pre = la colazione già pianificata, 2-3 h prima della partenza. Caffeina 150-190 mg (2-2,5 mg/kg) se parti presto.",
        intra_note="3 gel + 1,5 L di isotonica + 1 banana su 3 h: ~63 g di carboidrati/ora, adatto a un ritmo facile con tetto 175 bpm.",
        intra=[("Gel (1 pz = 32 g)", 96), ("Bevanda isotonica", 1500), ("Banana", 120)],
        post_note="Entro 30-45 minuti dall'arrivo.",
        post=[("Whey", 30), ("Corn flakes s/zuccheri", 60), ("Latte di soia", 250)]),
      insight=None, recovery=None),
 dict(iso="2026-09-27", titolo="Domenica 27 settembre", tag="media", dot="crit",
      kcal=3454, C=530, P=136, G=88, cpk=7.0, ppk=1.8,
      needn="2.289 kcal di base (BMR × 1,3) + <b>1.165 kcal</b> di corsa. Il fueling ne copre una parte: vedi sotto.",
      sessions=[
        dict(icon="🏃", nome="facile collinare", sub="Corsa · pianificata", kcal="1.165 kcal",
             metrics=["⏱ 1:20", "📏 ~14,2 km", "⚡ TSS 89,1"],
             nota="1 kcal/kg/km × 14,2 km stimati, <b>+8,4% su strada</b> (media aggiornata a sette verifiche, era +8,7%). Dopo 15′ di riscaldamento in pianura, 3 salite corte (&lt;1 km) e non ripide. &lt;180 bpm in pianura, ~185 bpm in salita."),
      ],
      flags=[("warnb", "⚠️ <b>Il weekend 26-27/09 ripete esattamente la struttura del 19-20/09</b>: 3 h di bici il sabato, corsa la domenica. Quel weekend aveva prodotto <b>HRV 48 ms «Low»</b>, sonno 6h26 e REM al 4%. Oggi si parte da una condizione molto migliore (HRV 121, REM 17%), ma la variabile da controllare è la stessa: entrambe le notti del 19-20/09 sono iniziate <b>dopo mezzanotte</b>."),
             ("dev", "📐 <b>Distanza stimata, non pianificata.</b> TrainingPeaks dà solo la durata (1:20) e 89,1 TSS; i 14,2 km derivano dal passo tenuto sulle collinari precedenti. Se il percorso è più duro del previsto la spesa sale, non scende.")],
      fuel=dict(titolo="⚡ Fueling della corsa collinare",
        pre="Pre = la colazione già pianificata, 2-3 h prima. Sul collinare meglio leggera: niente grassi né fibre nelle ultime 2 h.",
        intra_note="1 gel a metà + 500 ml di isotonica: ~41 g di carboidrati/ora, sufficienti per 1h20 a intensità controllata.",
        intra=[("Gel (1 pz = 32 g)", 32), ("Bevanda isotonica", 500)],
        post_note="Entro 30-45 minuti dall'arrivo.",
        post=[("Whey", 30), ("Banana", 120)]),
      insight=None, recovery=None),
 dict(iso="2026-09-28", titolo="Lunedì 28 settembre", tag="leggera", dot="good",
      kcal=2579, C=265, P=151, G=102, cpk=3.5, ppk=2.0,
      needn="2.289 kcal di base (BMR × 1,3) + <b>290 kcal</b> di forza. Giornata a basso carboidrato: proteine a <b>2,0 g/kg</b> come in tutti i giorni di forza.",
      sessions=[
        dict(icon="🏋️", nome="Gambe Mantenimento", sub="Forza · pianificata", kcal="290 kcal",
             metrics=["⏱ ~0:57", "⚡ TSS 20,0"],
             nota="309 kcal/h (quattro misure COROS, range 275-337) × ~57′. Durata non indicata su TrainingPeaks."),
      ],
      flags=[("dev", "🔵 <b>È la seduta saltata martedì 22/09 e mai recuperata</b>, ora riprogrammata. A differenza della Z4 bici e della corsa — traslate di un giorno e svolte — questa era rimasta indietro."),
             ("warnb", "⚠️ <b>Gambe il giorno dopo un weekend da 3 h di bici più corsa collinare.</b> Se domenica sera il sonno scende sotto le 7 h o l'HRV esce dal range, questa è la seduta da spostare al 29 o al 30, non il nuoto di martedì.")],
      insight=None, recovery=None),
 dict(iso="2026-09-29", titolo="Martedì 29 settembre", tag="media", dot="warn",
      kcal=2797, C=363, P=136, G=89, cpk=4.8, ppk=1.8,
      needn="2.289 kcal di base (BMR × 1,3) + <b>508 kcal</b> di nuoto a piano. Se il nuoto salta, togli 508 kcal (≈125 g di carboidrati).",
      sessions=[
        dict(icon="🏊", nome="braccia+A2", sub="Nuoto in vasca · pianificata", kcal="508 kcal",
             metrics=["⏱ 0:46", "📏 3,6 km", "⚡ TSS 71,8"],
             nota="141 kcal/km × 3,6 km.<br>200 riscaldamento · 6×50 tecnica con boccaglio (bracciata solo sub, solo prima fase di spinta, solo ultima) · 6×50 R8 · 12×50 pale+pull · 6×50 A2 agile · 8×50 pale+pull · 4×50 A2 · 4×50 pale+pull · 2×50 A2 · 10×100 con boccaglio ampiezza max."),
      ],
      flags=[("warnb", "🔴 <b>Settima vasca a piano.</b> È la seduta più lunga del blocco (3,6 km, 71,8 TSS) e arriva due giorni dopo il weekend carico: storicamente è la prima candidata a saltare. Ma il 23/09 la vasca è arrivata spontaneamente: il problema non è nuotare, è nuotare <b>nel giorno scritto sul calendario</b>.")],
      insight=None, recovery=None),
 dict(iso="2026-09-30", titolo="Mercoledì 30 settembre", tag="media", dot="warn",
      kcal=3638, C=568, P=136, G=91, cpk=7.5, ppk=1.8,
      needn="2.289 kcal di base (BMR × 1,3) + <b>1.349 kcal</b> di bici. Il fueling ne copre una parte: vedi sotto.",
      sessions=[
        dict(icon="🚴", nome="variazioni Z2/Z3", sub="Bici · pianificata · ⭐ principale", kcal="1.349 kcal",
             metrics=["⏱ 1:48", "⚡ TSS 88,4", "NP ~208 W"],
             nota="NP = 297 × √(0,8842 / 1,8) = 208 W → 208 × 6.480 / 1.000 = <b>1.349 kcal</b>. Variazioni da fare in pianura. Sotto le 3 h non si applica il +5%, ma con dislivello marcato il 23/09 ha dato −6,0%: se il percorso sale, aggiungi ~80 kcal."),
      ],
      flags=[("dev", "🔀 <b>Due voci «variazioni Z2/Z3» sullo stesso giorno = alternative, non si sommano.</b> La seconda vale 0:57 e 49,63 TSS (~760 kcal): se scegli quella, togli <b>589 kcal</b> dal fabbisogno (≈145 g di carboidrati) e dimezza il fueling."),
             ("warnb", "🔴 <b>Avvia l'attività sull'orologio COROS.</b> Il 23/09 l'orologio era al polso e ha registrato HR max 162, ma nessun record: la bici è sparita dal modello del carico. È la causa accertata di <b>~878 TSS invisibili</b>, tutti in bici.")],
      fuel=dict(titolo="⚡ Fueling della bici",
        pre="Pre = il pasto già pianificato, 2-3 h prima.",
        intra_note="2 gel + 750 ml di isotonica su 1h48: ~53 g di carboidrati/ora, adeguati a un lavoro Z2/Z3.",
        intra=[("Gel (1 pz = 32 g)", 64), ("Bevanda isotonica", 750)],
        post_note="Entro 30-45 minuti dall'arrivo.",
        post=[("Whey", 30), ("Gallette di riso", 20)]),
      insight=None, recovery=None),
 dict(iso="2026-10-01", titolo="Giovedì 1 ottobre", tag="intensa", dot="crit",
      kcal=3331, C=492, P=136, G=91, cpk=6.5, ppk=1.8,
      needn="2.289 kcal di base (BMR × 1,3) + <b>1.042 kcal</b> di corsa. Il post-seduta ne copre una parte: vedi sotto.",
      sessions=[
        dict(icon="🏃", nome="progressivo Z3 → Z5", sub="Corsa · pianificata", kcal="1.042 kcal",
             metrics=["⏱ 0:56", "📏 12,70 km", "⚡ TSS 74,6"],
             nota="1 kcal/kg/km × 12,70 km, <b>+8,4% su strada</b>. <b>La corsa più intensa del blocco</b>: 74,6 TSS in 56 minuti sono 80 TSS/ora, contro i 40 della collinare di domenica. Arriva il giorno dopo la bici a variazioni — la qualità va tutta qui, non nel mercoledì."),
      ],
      flags=[("warnb", "🔴 <b>Ultimo giorno della finestra, e il più esigente.</b> Nelle ultime due settimane ogni progressivo è stato corso più forte del previsto: il «recupero attivo» del 24/09 è finito a HR 164 e +56% di TSS. Su un Z3 → Z5 il margine per sbagliare in eccesso non c'è: la parte veloce sta negli ultimi 2-3 km, non dal quinto."),
             ("dev", "📐 <b>Piano caricato fino al 02/10</b> (nuoto «C1/B2+B1», 3,4 km, 79,96 TSS). La finestra della dashboard si chiude qui: il 02/10 entra al prossimo run.")],
      fuel=dict(titolo="⚡ Fueling del progressivo",
        pre="Pre = il pasto già pianificato, 2-3 h prima. Sotto l'ora non serve carico aggiuntivo, serve solo essere leggeri: niente grassi né fibre nelle ultime 2 h.",
        intra_note="Intra = solo acqua. Cinquantasei minuti con la parte intensa in coda non richiedono carboidrato in corsa: un gel preso al ventesimo minuto arriva in circolo quando la seduta è già finita.",
        intra=[],
        post_note="Entro 30-45 minuti. Qui conta: è l'unica seduta della settimana che arriva in Z5.",
        post=[("Whey", 30), ("Banana", 140)]),
      insight=None, recovery=None),
]
